language: elixir
sudo: false
elixir:
  - 1.3.4
  - 1.4.0
otp_release:
  - 18.3
  - 19.2
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
  - MIX_ENV=test mix coveralls.travis
